### ISSUE TITLE
Account registration

### ISSUE THREAD

**Issue by emmy-codes** [emmy-codes/coscalendar#3]
As an Unauthenticated User, I wish to register an account by clicking Register so I can join the community

Definition of Done:

1. Form with registration details is visible ✅
2. Filling in the form creates an account AND signs the user in (update: user is redirected to login page instead) ✅
3. Signing in shows user a confirmation/welcome (update: upon successful account creation user is shown a success message)

**Comment by jovanbachtiar** [comment]
Can I work on this issue?

**Comment by emmy-codes** [comment]
Hi @jovanbachtiar ! This repo is my school project so I have to do all of these for myself 😁 thanks for taking an interest!
